#!/bin/bash
# made by ForgeN

echo "Enter the first three octets of the IP range (e.g. 192.168.1):"
read ip_range
echo " "
# Save the output of the ping command to a file
echo " " > live_hosts.txt

parallel -j 255 ping -c 1 -W 1 ${ip_range}.{} ::: {1..255} >> output.txt 2>/dev/null;

# Extract only the live hosts from the ping output
grep "bytes from" output.txt | cut -d " " -f 4 | cut -d ":" -f 1 > live_hosts.txt

# Check for the openness of HTTP and HTTPS ports for each live host
# and store the results in a table
echo "Host | HTTP | HTTPS" > results.txt
while read host; do
  http='No'
  https='No'
  if nc -z -w 1 ${host} 80; then
    http='Yes'
  fi
  if nc -z -w 1 ${host} 443; then
    https='Yes'
  fi
  echo "${host} | ${http} | ${https}" >> results.txt
done <live_hosts.txt

# Format the table using the column command
column -t -s "|" results.txt

# Clean up
rm output.txt
rm live_hosts.txt
rm results.txt
